### PR TITLE
Simplify CSS, rename template

### PR DESCRIPTION
**Pull request by pyrmont**
Because of course I would do this.

### CODE REVIEW

**Comment by pyrmont** [comment]
So, what you think of this?

**Comment by ashmaroli** [comment]
I'm waiting for the verdict on the new formatter I proposed.
In current state, removing the borders and padding is not very aesthetically sound when accessing `http://localhost:9292/perl?line_numbers=true&theme=monokai&juxtaposed=true`

**Comment by ashmaroli** [comment]
Can the template be named `lexer_juxtaposed` instead?

**Comment by pyrmont** [comment]
@ashmaroli Done :)

**Comment by ashmaroli** [comment]
On using the latest `upstream/master` branch and testing http://localhost:9292/ruby?line_numbers=true&juxtaposed=true I see the following:
image

Notice how the tables are squashed into each other..
I think, I should reject this PR and try to reduce CSS in the base branch directly.. 
whatsay?

**Comment by pyrmont** [comment]
@ashmaroli Yep, that's cool with me!

**Comment by ashmaroli** [comment]
Thanks for understanding.

**Pull request closed without merging**
